### PR TITLE
Fix issue: not working with java 11 64bits

### PR DESCRIPTION
**Pull request by tatery**
I'm not able to open serial ports on 64bits Debian based Linux with 64bits java 11 version.
This PR fixes issue mentioned above. I have updated libraries version and bumped up source/target java version to 11 since java 1.7 is outdated.

### CODE REVIEW

**Comment by nyholku** [comment]
Why are all those jar files changed? They are history so IMO they should not be changed.

**Comment by tatery** [comment]
This was my first time using github codespace to create this PR, and it is likely that these jars were deleted accidentally. I will try to restore them.

**Comment by tatery** [comment]
@nyholku all historical files have been restored

**Comment by tatery** [comment]
@nyholku Hi. It's been a while since this PR was submitted. Are you planning to merge it and release a new version of the library? Java evolves quickly, and the last official release of this library is for Java 1.7

**Review by nyholku — APPROVED** [review]
Cannot really test this ATM, but looks safe enough for me.

**Comment by nyholku** [comment]
Cannot really test this but looks safe enough for me.

**Comment by tatery** [comment]
@nyholku Thank you very much. Could you also make a new release available on the maven repository?

**Pull request merged**
